
project:
  type: book
  output-dir: docs

book:
  title: "LSTM Recurrent Neural Networks"
  author: "Kevin Waisfeld; Moise Brutus; Michael Nhliziyo"
  date: "9/28/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - Data.qmd
    - methodology.qmd
    - Analysis.qmd
    - results.qmd
    - Conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

