# References {.unnumbered}

1.  A. Sherstinsky, "Fundamentals of Recurrent Neural Network (RNN) and Long Short-Term Memory (LSTM) network," Physica D: Nonlinear Phenomena, vol. 404, p. 132306, Mar. 2020, doi:<https://doi.org/10.1016/j.physd.2019.132306>.

2.  P. Chaajer, M. Shah, and A. Kshirsagar, "The applications of artificial neural networks, support vector machines, and long-short term memory for stock market prediction," Decision Analytics Journal, p. 100015, Nov. 2021, doi: <https://doi.org/10.1016/j.dajour.2021.100015>.

3.  M. Kumbure, C. Lohrmann, P. Luukka, and J. Porras, "Machine learning techniques and data for stock market forecasting: A literature review," Expert Systems with Applications, vol. 197, p. 116659, Jul. 2022, doi: <https://doi.org/10.1016/j.eswa.2022.116659>

4.  Qiao, R., Chen, W., & Qiao, Y. (2022). "Prediction of stock return by LSTM neural network," Applied Artificial Intelligence, 36(1). doi: <https://doi.org/10.1080/08839514.2022.2151159>.

5.  Fjellström, C. (2022, January 20). "Long short-term memory neural network for Financial Time Series," arXiv.org. doi: <https://doi.org/10.48550/arXiv.2201.08218>.

6.  Mehlig, B. (2021, October 27). "Machine learning with neural networks," arXiv.org. doi: <https://doi.org/10.48550/arXiv.1901.05639>.

7.  Staudemeyer, R., Morris, E. (2019, September 23). "Understanding LSTM -- a tutorial into Long Short-Term Memory Recurrent Neural Networks," ArXiv.org. doi: <https://doi.org/10.48550/arXiv.1909.09586>

8.  Sharma, S., Athaiya, A. (2020, April). "ACTIVATION FUNCTIONS IN NEURAL NETWORKS," International Journal of Engineering Applied Sciences and Technology. 04. 310-316. 10.33564/IJEAST.2020.v04i12.054.

9.  Harris, C. R., Millman, K. J., van der Walt, S. J.,
    Gommers, R., Virtanen, P., Cournapeau, D., ... Oliphant, T. E. (2020). Array
    programming with NumPy. Nature, 585, 357--362. <https://doi.org/10.1038/s41586-020-2649-2>

10. McKinney, W., & others. (2010). Data structures for
    statistical computing in python. In Proceedings of the 9th Python in Science
    Conference (Vol. 445, pp. 51--56).

11. Abadi, Mart&#x27;in, Barham, P., Chen, J., Chen, Z.,
    Davis, A., Dean, J., ... others. (2016). Tensorflow: A system for large-scale
    machine learning. In 12th \$USENIX\$ Symposium on Operating Systems Design and
    Implementation (\$OSDI\$ 16) (pp. 265--283).

12. Pedregosa, F., Varoquaux, Ga"el, Gramfort, A.,
    Michel, V., Thirion, B., Grisel, O., ... others. (2011). Scikit-learn: Machine
    learning in Python. Journal of Machine Learning Research, 12(Oct), 2825--2830.

13. Chollet, F., & others. (2015). Keras. GitHub.
    Retrieved from <https://github.com/fchollet/keras>.

14. https://www.blueskycapitalmanagement.com/machine-learning-in-finance-why-you-should-not-use-lstms-to-predict-the-stock-market/
